services:
  gym-manager-api-pg:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gym_manager-api
      - DATABASE_URL=postgresql://docker:docker@localhost:5432/gym_manager-api
